name: Test FastAPI Code

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test FastAPI Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r atlas-api/requirements.txt
          pip install pytest


      - name: Start FastAPI server
        run: uvicorn api.main:app --host 0.0.0.0 --port 8000 &

      - name: Wait for server to start
        run: sleep 5

      - name: Run tests
        run: |
          pytest atlas-api/api/test.py
